name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Create Package
      run: |
        cd styles
        zip -r Turkish.zip Turkish
        mv Turkish.zip ../

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          Turkish.zip
          library.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
